# Generated by Django 4.2 on 2024-05-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('admin', 'Администратор')], default='manager', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
