# Generated by Django 4.2 on 2024-04-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail_app', '0003_mailingsettings_client_alter_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
