# Generated by Django 4.2 on 2024-04-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail_app', '0004_mailingmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingmessage',
            name='message',
            field=models.TextField(verbose_name='Текст письма'),
        ),
    ]
