# Generated by Django 4.2 on 2024-05-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail_app', '0006_mailingsettings_mail_alter_mailingsettings_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='client',
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='client',
            field=models.ManyToManyField(to='e_mail_app.client', verbose_name='Получатель'),
        ),
    ]
