# Generated by Django 4.2 on 2024-05-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail_app', '0007_remove_mailingsettings_client_mailingsettings_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='period',
            field=models.CharField(choices=[('per_day', 'раз в день'), ('per_week', 'раз в неделю'), ('per_month', 'раз в месяц')], default='per_month', max_length=12, verbose_name='Периодичность рассылки'),
        ),
    ]
