# Generated by Django 4.2 on 2024-05-04 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail_app', '0008_alter_mailingsettings_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='sending_time',
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Конец рассылки'),
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало рассылки'),
        ),
    ]
