# Generated by Django 4.2 on 2024-05-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail_app', '0009_remove_mailingsettings_sending_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
    ]
