# Generated by Django 4.2 on 2024-05-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail_app', '0011_logger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_mail_app.mailingsettings', verbose_name='Рассылка'),
        ),
    ]
