# Generated by Django 4.2 on 2024-05-17 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail_app', '0012_alter_logger_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='next_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата следующей рассылки'),
        ),
    ]
