# Generated by Django 4.2 on 2024-05-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail_app', '0013_mailingsettings_next_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='mailing_name',
            field=models.CharField(default='mailing_name', max_length=50, verbose_name='Название рассылки'),
        ),
    ]
