# Generated by Django 4.2 on 2024-05-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail_app', '0014_mailingsettings_mailing_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='is_active',
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
    ]
