# Generated by Django 4.2 on 2024-05-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail_app', '0016_remove_mailingmessage_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('toggle_active', 'выключить рассылку')], 'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
    ]
