# Generated by Django 4.2 on 2024-05-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_toggle_published', 'изменить статус публикации')], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
